### ISSUE TITLE
PHP Data Objects abstraction layer to allow more database types

### ISSUE THREAD

**Issue by perjonsson** [melt/melt#11]
A suggestion for Melt would be to implement PHP Data Objects (PDO) to support additional database types such as PostgreSQL and SQLite. This is currently supported by Yii and Symfony.

**Comment by hnsl** [comment]
Melt is heavily dependent on more advanced MySQL to automatically solve as many problems as possible. If this features can be decoupled from melt\Model and the db api is rewritten to handle database abstractly this could be implemented. Since Melt Software has no use for this, nor time to add this feature has to be written by the community if the community requires it.

**Comment by perjonsson** [comment]
Added to the faq section of the documentation
